sudo: false
dist: trusty
language: python
python:
    - "2.7.13"
    - "3.6.1"
install:
    - pip install flake8
    - python setup.py -q install
before_script:
    # stop the build if there are Python syntax errors
    - flake8 . --count --select=E901,E999 --statistics
    # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-line-length=127 --statistics
script:
    - python test/test_IBMQuantumExperience.py
notifications:
    on_success: change
    on_failure: always
